### ISSUE TITLE
a bug?

### ISSUE THREAD

**Issue by haoxusci** [israfelsr/cs231n-2019#5]
I ve tried to run your solution, it seems a bug here https://github.com/israfelsr/CS231n/blob/affdddb2785f64b26847a945191f1d1780132be6/assignment1/cs231n/classifiers/neural_net.py#L132. Should the axis=c be axis=1 instead?

**Comment by israfelsr** [comment]
Sure! A typo haha I would fix it. Thanks for the comment :)
